// This file is auto-generated by @hey-api/openapi-ts

export { type Options, postbacksAccept, v1ProgramsIndex, v1ProgramsStore } from './sdk.gen';
export type { ClientOptions, PostbacksAcceptData, PostbacksAcceptError, PostbacksAcceptErrors, PostbacksAcceptResponse, PostbacksAcceptResponses, V1ProgramsIndexData, V1ProgramsIndexResponse, V1ProgramsIndexResponses, V1ProgramsStoreData, V1ProgramsStoreResponse, V1ProgramsStoreResponses } from './types.gen';
