// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { PostbacksAcceptData, PostbacksAcceptErrors, PostbacksAcceptResponses, V1ProgramsIndexData, V1ProgramsIndexResponses, V1ProgramsStoreData, V1ProgramsStoreResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postbacksAccept = <ThrowOnError extends boolean = false>(options: Options<PostbacksAcceptData, ThrowOnError>): RequestResult<PostbacksAcceptResponses, PostbacksAcceptErrors, ThrowOnError> => (options.client ?? client).post<PostbacksAcceptResponses, PostbacksAcceptErrors, ThrowOnError>({ url: '/v1/postbacks/{vendor}', ...options });

/**
 * Fetch zero to many `programs` resources
 */
export const v1ProgramsIndex = <ThrowOnError extends boolean = false>(options?: Options<V1ProgramsIndexData, ThrowOnError>): RequestResult<V1ProgramsIndexResponses, unknown, ThrowOnError> => (options?.client ?? client).get<V1ProgramsIndexResponses, unknown, ThrowOnError>({ url: '/v1/programs', ...options });

/**
 * Create a new `programs` resource
 */
export const v1ProgramsStore = <ThrowOnError extends boolean = false>(options: Options<V1ProgramsStoreData, ThrowOnError>): RequestResult<V1ProgramsStoreResponses, unknown, ThrowOnError> => (options.client ?? client).post<V1ProgramsStoreResponses, unknown, ThrowOnError>({
    url: '/v1/programs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
