// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api' | (string & {});
};

export type PostbacksAcceptData = {
    body?: never;
    path: {
        vendor: string;
    };
    query?: never;
    url: '/v1/postbacks/{vendor}';
};

export type PostbacksAcceptErrors = {
    422: {
        message: string;
    };
};

export type PostbacksAcceptError = PostbacksAcceptErrors[keyof PostbacksAcceptErrors];

export type PostbacksAcceptResponses = {
    202: {
        data: {
            id: number;
            vendor: string;
            external_id: string;
            status: string;
        };
    };
};

export type PostbacksAcceptResponse = PostbacksAcceptResponses[keyof PostbacksAcceptResponses];

export type V1ProgramsIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/programs';
};

export type V1ProgramsIndexResponses = {
    200: {
        data: Array<{
            type: string;
            id: string;
            attributes: {
                name: string;
                slug: string;
                status: string;
                createdAt: string;
                updatedAt: string;
            };
            links: {
                self: string;
            };
        }>;
        links: {
            first: string;
            last: string;
            prev: string | null;
            next: string | null;
        };
        meta: {
            page: {
                currentPage: number;
                from: number | null;
                lastPage: number;
                perPage: number;
                to: number | null;
                total: number;
            };
        };
        jsonapi: {
            version: string;
        };
    };
};

export type V1ProgramsIndexResponse = V1ProgramsIndexResponses[keyof V1ProgramsIndexResponses];

export type V1ProgramsStoreData = {
    body: {
        /**
         * The JSON:API resource object to create.
         */
        data: {
            type: string;
            attributes: {
                name: string;
                slug: string;
                status?: string;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/v1/programs';
};

export type V1ProgramsStoreResponses = {
    200: {
        data: {
            type: string;
            id: string;
            attributes: {
                name: string;
                slug: string;
                status: string;
                createdAt: string;
                updatedAt: string;
            };
            links: {
                self: string;
            };
        };
        jsonapi: {
            version: string;
        };
    };
};

export type V1ProgramsStoreResponse = V1ProgramsStoreResponses[keyof V1ProgramsStoreResponses];
